AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  An AWS Serverless Application that uses the ASP.NET Core framework running in
  Amazon Lambda.

Globals:
  Api:
    Cors: 
      AllowOrigin: "'*'"
      AllowHeaders: "'*'"

Parameters:
  AspNetCoreEnv:
    Type: String
    Default: Development
  UserpoolArn:
    Type: String
    Default: arn:aws:cognito-idp:ap-southeast-2:869393488965:userpool/ap-southeast-2_hKuSDoKtV

Resources:

  TokenManagerApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Auth:
        DefaultAuthorizer: CognitoUserPool
        Authorizers:
          CognitoUserPool:
            UserPoolArn: !Ref UserpoolArn
        AddDefaultAuthorizerToCorsPreflight: false

  AspNetCoreApi:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: tokenManagerApi::tokenManagerApi.LambdaEntryPoint::FunctionHandlerAsync
      Runtime: dotnetcore3.1
      CodeUri: ''
      MemorySize: 1024
      Timeout: 30
      Role: null
      Policies:
        - AWSLambda_FullAccess
        - AWSLambdaDynamoDBExecutionRole
        - AmazonDynamoDBFullAccess
        - AmazonCognitoPowerUser
        - Statement:
          - Sid: SSMParametersPolicy
            Effect: Allow
            Action:
            - ssm:GetParameter
            - ssm:GetParameters
            - ssm:GetParametersByPath
            Resource: '*'
      Environment:
        Variables:
          ASPNETCORE_ENVIRONMENT: !Ref AspNetCoreEnv
      Events:

        #------------- Auth -------------
        AuthLogin:
          Type: Api
          Properties:
            Path: '/api/auth/login'
            Method: Post
            RestApiId: !Ref "TokenManagerApi" 
            Auth:
              Authorizer: 'NONE'

        #------------- Tokens -------------
        TokensListToken:
          Type: Api
          Properties:
            Path: '/api/tokens'
            Method: Get
            RestApiId: !Ref "TokenManagerApi" 

        TokensAddUpdateToken:
          Type: Api
          Properties:
            Path: '/api/tokens'
            Method: Post
            RestApiId: !Ref "TokenManagerApi" 

        TokensDeleteToken:
          Type: Api
          Properties:
            Path: '/api/tokens'
            Method: Delete
            RestApiId: !Ref "TokenManagerApi" 

        TokensValidateToken:
          Type: Api
          Properties:
            Path: '/api/tokens/validate'
            Method: Post
            RestApiId: !Ref "TokenManagerApi"
            Auth:
              Authorizer: 'NONE'


  # ---------------- DYNAMO TABLE DEFINITIONS ----------------

  TokensTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Delete
    Properties:
      AttributeDefinitions:
        - AttributeName: AppName
          AttributeType: S
        - AttributeName: Token
          AttributeType: S
      KeySchema:
        - AttributeName: AppName
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: TokenIndex
          KeySchema:
          - AttributeName: Token
            KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2
      ProvisionedThroughput: 
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: tokenMgr-tokens

Outputs:
  ApiURL:
    Description: raw API endpoint URL for this environment
    Value: !Sub 'https://${TokenManagerApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/'